name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint & Build
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: lts/*
      - run: pnpm install
      - run: pnpm type-check
      - run: pnpm lint -f gha --max-warnings 0
      - run: pnpm prepublishOnly

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    name: Node.js ${{ matrix.node }} / ${{ matrix.os }}
    strategy:
      # A test failing on windows doesn't mean it'll fail on macos. It's useful to let all tests run to its completion to get the full picture
      fail-fast: false
      matrix:
        # Run the testing suite on each major OS with the latest LTS release of Node.js
        os: [macos-latest, ubuntu-latest, windows-latest]
        node: [lts/*]
        # It makes sense to also test the oldest, and latest, versions of Node.js, on ubuntu-only since it's the fastest CI runner
        include:
          - os: ubuntu-latest
            # Test the oldest LTS release of Node that's still receiving bugfixes and security patches, versions older than that have reached End-of-Life
            node: lts/-2
          - os: ubuntu-latest
            # Test the actively developed version that will become the latest LTS release next October
            node: current
    steps:
      # It's only necessary to do this for windows, as mac and ubuntu are sane OS's that already use LF
      - name: Set git to use LF
        if: matrix.os == 'windows-latest'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: ${{ matrix.node }}
      - run: pnpm install
      - run: pnpm test
